setup_admin
HopeeRuby/beauty_care pull request #12
Opened 2023-04-21 06:17 UTC by hongthamnguyen2k

#4

- Setup gem https://github.com/heartcombo/devise 
- Create Admin tables
- Update file seed.rb (use faker, factory_bot create sample admin) ==> (Khoa & anh NAnh)
- Design login form, allow admin login to admin page and logout ==> (Thắm)

2023-04-21 08:31 UTC, hongthamnguyen2k commented on app/controllers/application_controller.rb
>  class ApplicationController < ActionController::Base
rubocop said: 1 offense detected: Extra empty line detected at class body beginning.

2023-04-21 09:39 UTC, khoa250200 approved these changes

2023-04-21 10:42 UTC, anhpn0712 approved these changes

2023-04-24 03:16 UTC, KhoaNDAHopee requested changes

2023-04-24 03:16 UTC, KhoaNDAHopee commented on app/assets/javascript/admin/js/main.js
Check indent

2023-04-24 03:16 UTC, KhoaNDAHopee commented on app/assets/stylesheets/admin/application.scss
> +  background-image: url("assets/style/images/bg_1.jpg")
Don't use background-image for all class .img on all page (should be for login page)

2023-04-24 03:16 UTC, KhoaNDAHopee commented on app/models/admin.rb
> +class Admin < ApplicationRecord
Should be validate for some fields

2023-04-24 03:16 UTC, KhoaNDAHopee commented on app/views/devise/sessions/new.html.erb
> +   <head>
Header should be in layout, not here.

2023-04-24 03:16 UTC, KhoaNDAHopee commented on app/views/shared/partials/_navbar.html.erb
> +        <span><%= link_to "Logout", destroy_admin_session_path, class: "mdi mdi-logout me-1  dropdown-item notify-item" %></span>
Check indent.

2023-04-24 03:16 UTC, KhoaNDAHopee commented on config/database.yml
Don't push your local configs to github

2023-04-24 03:16 UTC, KhoaNDAHopee commented on spec/factories/admins.rb
> +    first_name {Faker::Name.first_name}
Check rubocop, should be ``{ Faker::Name.first_name }``

2023-04-24 03:16 UTC, KhoaNDAHopee commented on spec/factories/admins.rb
> +require 'faker'
No need require here.

2023-04-25 01:05 UTC, KhoaNDAHopee requested changes

2023-04-25 01:05 UTC, KhoaNDAHopee commented on app/views/devise/sessions/new.html.erb
> +<%= render partial: '/layouts/login/devise'%>
Muốn sử dụng 1 layout khác (thay vì chung layout admin) cho devise sử dụng cách sau https://github.com/heartcombo/devise/wiki/How-To%3A-Create-custom-layouts

2023-04-25 06:14 UTC, KhoaNDAHopee commented on config/routes.rb
> +        resources :admins
Check indent

2023-04-25 06:23 UTC, merged