Issue 13 allow administrator with crud actions
HopeeRuby/beauty_care pull request #14
Opened 2023-04-28 03:30 UTC by khoa250200

Please review my code before merge into develop

2023-04-28 06:03 UTC, anhpn0712 approved these changes

2023-04-28 08:41 UTC, hongthamnguyen2k approved these changes

2023-05-04 04:15 UTC, KhoaNDAHopee requested changes
Please check my comments:
<img width="261" alt="Screen Shot 2023-05-04 at 11 13 12" src="https://user-images.githubusercontent.com/115602568/236111164-00c16d00-1cac-4139-a145-6b17c61433f9.png">
- Please remove unnecessary items on left menu
<img width="1694" alt="Screen Shot 2023-05-04 at 11 14 40" src="https://user-images.githubusercontent.com/115602568/236111286-2a6019aa-d7a3-4ec2-8ec4-a821b7f7b01a.png">
- Please implement UI for CURD admin

2023-05-04 04:15 UTC, KhoaNDAHopee commented on app/assets/stylesheets/access_denied.scss
> +font-family: 'Ropa Sans', sans-serif;
Please check indent

2023-05-04 04:15 UTC, KhoaNDAHopee commented on app/controllers/administrator/admins_controller.rb
> +      @admins = Admin.all
Please use pagination

2023-05-04 04:15 UTC, KhoaNDAHopee commented on app/models/admin.rb
> +  VALID_EMAIL_REGEX = /\A[^@\s]+@[^@\s]+\z/
Try with ``devise::email_regexp``

2023-05-04 04:15 UTC, KhoaNDAHopee commented on spec/factories/admins.rb
> +    phone { '1111222233' }
Why hard set for phone?

2023-05-04 04:15 UTC, KhoaNDAHopee commented on spec/factories/admins.rb
> +    status { 'active' }
Why hard set for status?

2023-05-04 04:15 UTC, KhoaNDAHopee commented on spec/factories/admins.rb
> +    role { 'admin' }
Why hard set for role?

2023-05-04 04:15 UTC, KhoaNDAHopee commented on db/seeds.rb
>    create(:admin)
If you want create admin with role: admin, status: active
https://devhints.io/factory_bot -> use with options
<img width="415" alt="Screen Shot 2023-05-04 at 11 00 38" src="https://user-images.githubusercontent.com/115602568/236110069-11bdf43a-ff80-478b-bdca-32f76038dc10.png">
```
create(:admin, role: 'admin', status: 'active')
```

2023-05-04 04:15 UTC, KhoaNDAHopee commented on spec/requests/admins_controller.rb
> +# frozen_string_literal: true
Refactor this file try with https://devhints.io/factory_bot

2023-05-04 04:15 UTC, KhoaNDAHopee commented on spec/requests/admins_controller.rb
> +    Admin.create(
Use factory_bot

2023-05-04 04:15 UTC, KhoaNDAHopee commented on spec/requests/admins_controller.rb
> +# frozen_string_literal: true
Add _spec to file name, rspec can't scan this file and run test.
<img width="744" alt="Screen Shot 2023-05-04 at 11 07 01" src="https://user-images.githubusercontent.com/115602568/236110594-08824baa-e126-42c7-9c12-c9ecc2c8a575.png">

2023-05-04 04:15 UTC, KhoaNDAHopee commented on spec/factories/admins.rb
> +# frozen_string_literal: true
Update password field

2023-05-11 04:28 UTC, merged